server:
  port: 3000
spring:
  application:
    name: oreo-wmcw-redis
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
      timeout: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
