server:
  port: 6000
spring:
  application:
    name: oreo-wmcw-hotel
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: localhost
    session:
      store-type: redis
  http:
    encoding:
      force: true
      charset: utf-8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka